-- =========================================================
-- HOSPITAL ROSTERING SYSTEM (Oracle SQL)
-- Entities (no Certification table)
-- =========================================================

-- Optional: drop in dependency order (uncomment if needed)
DROP TABLE shift_swap_request CASCADE CONSTRAINTS;
DROP TABLE fairness_index CASCADE CONSTRAINTS;
DROP TABLE burnout_prediction CASCADE CONSTRAINTS;
DROP TABLE roster_rule CASCADE CONSTRAINTS;
DROP TABLE recovery_requirement CASCADE CONSTRAINTS;
DROP TABLE incident_exposure CASCADE CONSTRAINTS;
DROP TABLE wellness_score CASCADE CONSTRAINTS;
DROP TABLE workload_record CASCADE CONSTRAINTS;
DROP TABLE availability CASCADE CONSTRAINTS;
DROP TABLE leave_request CASCADE CONSTRAINTS;
DROP TABLE assignment CASCADE CONSTRAINTS;
DROP TABLE shift CASCADE CONSTRAINTS;
DROP TABLE staff CASCADE CONSTRAINTS;
DROP TABLE department CASCADE CONSTRAINTS;
DROP TABLE role CASCADE CONSTRAINTS;

-- =========================================================
-- 1) CORE REFERENCE TABLES
-- =========================================================

CREATE TABLE role (
  role_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name      VARCHAR2(60) NOT NULL UNIQUE,
  required_certification_level VARCHAR2(40), -- keep or remove if you don't want it
  default_shift_length_hours   NUMBER(2) CHECK (default_shift_length_hours BETWEEN 1 AND 24)
);

CREATE TABLE department (
  department_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name VARCHAR2(80) NOT NULL UNIQUE,
  location       VARCHAR2(120),
  min_staff_required_per_shift NUMBER(3) DEFAULT 0 CHECK (min_staff_required_per_shift >= 0)
);

-- =========================================================
-- 2) STAFF
-- =========================================================

CREATE TABLE staff (
  staff_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name     VARCHAR2(60) NOT NULL,
  last_name      VARCHAR2(60) NOT NULL,
  role_id        NUMBER NOT NULL,
  department_id  NUMBER NOT NULL,

  employment_type VARCHAR2(15) NOT NULL
    CHECK (employment_type IN ('FULL_TIME','PART_TIME','CASUAL','CONTRACT')),

  base_hours_per_week NUMBER(5,2) DEFAULT 0 CHECK (base_hours_per_week >= 0),
  max_hours_per_week  NUMBER(5,2) DEFAULT 0 CHECK (max_hours_per_week >= 0),

  hire_date      DATE DEFAULT SYSDATE,
  status         VARCHAR2(12) DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE','ON_LEAVE','TERMINATED')),

  CONSTRAINT staff_role_fk
    FOREIGN KEY (role_id) REFERENCES role(role_id),

  CONSTRAINT staff_department_fk
    FOREIGN KEY (department_id) REFERENCES department(department_id),

  CONSTRAINT staff_hours_chk
    CHECK (max_hours_per_week = 0 OR base_hours_per_week <= max_hours_per_week)
);

-- =========================================================
-- 3) SHIFT + ASSIGNMENT (Roster bridge)
-- =========================================================

CREATE TABLE shift (
  shift_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id  NUMBER NOT NULL,

  shift_start    TIMESTAMP NOT NULL,
  shift_end      TIMESTAMP NOT NULL,

  shift_type     VARCHAR2(10) NOT NULL
    CHECK (shift_type IN ('MORNING','EVENING','NIGHT','ON_CALL')),

  required_role_id NUMBER, -- optional: some shifts require a role
  required_staff_count NUMBER(3) DEFAULT 1 CHECK (required_staff_count >= 1),

  CONSTRAINT shift_department_fk
    FOREIGN KEY (department_id) REFERENCES department(department_id),

  CONSTRAINT shift_required_role_fk
    FOREIGN KEY (required_role_id) REFERENCES role(role_id),

  CONSTRAINT shift_time_chk
    CHECK (shift_end > shift_start)
);

CREATE TABLE assignment (
  assignment_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id       NUMBER NOT NULL,
  shift_id       NUMBER NOT NULL,

  assignment_status VARCHAR2(12) DEFAULT 'SCHEDULED'
    CHECK (assignment_status IN ('SCHEDULED','COMPLETED','SWAPPED','CANCELLED')),

  assigned_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
  swap_requested CHAR(1) DEFAULT 'N' CHECK (swap_requested IN ('Y','N')),

  CONSTRAINT assignment_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT assignment_shift_fk
    FOREIGN KEY (shift_id) REFERENCES shift(shift_id),

  -- prevent same staff assigned to same shift twice
  CONSTRAINT assignment_staff_shift_uk UNIQUE (staff_id, shift_id)
);

-- =========================================================
-- 4) LEAVE + AVAILABILITY
-- =========================================================

CREATE TABLE leave_request (
  leave_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id       NUMBER NOT NULL,

  leave_type     VARCHAR2(12) NOT NULL
    CHECK (leave_type IN ('ANNUAL','SICK','PARENTAL','UNPAID','OTHER')),

  start_date     DATE NOT NULL,
  end_date       DATE NOT NULL,

  approval_status VARCHAR2(10) DEFAULT 'PENDING'
    CHECK (approval_status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),

  requested_at   TIMESTAMP DEFAULT SYSTIMESTAMP,

  CONSTRAINT leave_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT leave_date_chk
    CHECK (end_date >= start_date)
);

CREATE TABLE availability (
  availability_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id        NUMBER NOT NULL,

  avail_date      DATE NOT NULL,
  available_start TIMESTAMP NOT NULL,
  available_end   TIMESTAMP NOT NULL,

  preference_level VARCHAR2(10) DEFAULT 'NEUTRAL'
    CHECK (preference_level IN ('PREFERRED','NEUTRAL','AVOID')),

  CONSTRAINT availability_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT availability_time_chk
    CHECK (available_end > available_start),

  -- one availability record per staff per date (you can relax this if you want multiple windows per day)
  CONSTRAINT availability_staff_date_uk UNIQUE (staff_id, avail_date)
);

-- =========================================================
-- 5) WORKLOAD + WELLNESS + INCIDENTS + RECOVERY
-- =========================================================

CREATE TABLE workload_record (
  workload_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id        NUMBER NOT NULL,

  week_start_date DATE NOT NULL,

  total_hours_worked      NUMBER(6,2) DEFAULT 0 CHECK (total_hours_worked >= 0),
  night_shifts_count      NUMBER(3) DEFAULT 0 CHECK (night_shifts_count >= 0),
  consecutive_days_worked NUMBER(3) DEFAULT 0 CHECK (consecutive_days_worked >= 0),
  overtime_hours          NUMBER(6,2) DEFAULT 0 CHECK (overtime_hours >= 0),

  CONSTRAINT workload_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT workload_staff_week_uk UNIQUE (staff_id, week_start_date)
);

CREATE TABLE wellness_score (
  wellness_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id       NUMBER NOT NULL,
  date_recorded  DATE NOT NULL,

  fatigue_score  NUMBER(2) CHECK (fatigue_score BETWEEN 1 AND 10),
  stress_score   NUMBER(2) CHECK (stress_score BETWEEN 1 AND 10),
  sleep_hours    NUMBER(4,1) CHECK (sleep_hours BETWEEN 0 AND 24),

  burnout_risk_level VARCHAR2(6)
    CHECK (burnout_risk_level IN ('LOW','MED','HIGH')),

  CONSTRAINT wellness_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT wellness_staff_date_uk UNIQUE (staff_id, date_recorded)
);

CREATE TABLE incident_exposure (
  incident_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id       NUMBER NOT NULL,
  shift_id       NUMBER, -- may tie to a shift, but optional
  recorded_at    TIMESTAMP DEFAULT SYSTIMESTAMP,

  trauma_level   VARCHAR2(6) NOT NULL
    CHECK (trauma_level IN ('LOW','MED','HIGH')),

  critical_event_flag CHAR(1) DEFAULT 'N' CHECK (critical_event_flag IN ('Y','N')),

  notes          VARCHAR2(500),

  CONSTRAINT incident_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT incident_shift_fk
    FOREIGN KEY (shift_id) REFERENCES shift(shift_id)
);

CREATE TABLE recovery_requirement (
  recovery_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id       NUMBER NOT NULL,

  effective_date DATE DEFAULT TRUNC(SYSDATE),

  min_rest_hours_required NUMBER(3) DEFAULT 0 CHECK (min_rest_hours_required BETWEEN 0 AND 168),
  cooldown_days_required  NUMBER(3) DEFAULT 0 CHECK (cooldown_days_required BETWEEN 0 AND 30),

  reason         VARCHAR2(200),

  CONSTRAINT recovery_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT recovery_staff_date_uk UNIQUE (staff_id, effective_date)
);

-- =========================================================
-- 6) RULES + PREDICTIONS
-- =========================================================

CREATE TABLE roster_rule (
  rule_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type     VARCHAR2(5) NOT NULL CHECK (rule_type IN ('HARD','SOFT')),
  description   VARCHAR2(300) NOT NULL,

  max_consecutive_nights NUMBER(2) CHECK (max_consecutive_nights BETWEEN 0 AND 14),
  min_rest_hours         NUMBER(3) CHECK (min_rest_hours BETWEEN 0 AND 168),
  max_weekly_hours       NUMBER(5,2) CHECK (max_weekly_hours BETWEEN 0 AND 168),

  is_active     CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N'))
);

CREATE TABLE burnout_prediction (
  prediction_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id         NUMBER NOT NULL,
  prediction_date  DATE NOT NULL,

  predicted_risk_score NUMBER(5,2) CHECK (predicted_risk_score BETWEEN 0 AND 100),
  recommended_action  VARCHAR2(200),

  model_version    VARCHAR2(30),

  CONSTRAINT prediction_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT prediction_staff_date_uk UNIQUE (staff_id, prediction_date)
);

-- =========================================================
-- 7) SWAPS + FAIRNESS
-- =========================================================

CREATE TABLE shift_swap_request (
  swap_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id   NUMBER NOT NULL,      -- staff requesting swap
  target_staff_id NUMBER,              -- optional: if requesting a specific person
  shift_id       NUMBER NOT NULL,

  approval_status VARCHAR2(10) DEFAULT 'PENDING'
    CHECK (approval_status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),

  requested_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
  reason         VARCHAR2(300),

  CONSTRAINT swap_requester_fk
    FOREIGN KEY (requester_id) REFERENCES staff(staff_id),

  CONSTRAINT swap_target_fk
    FOREIGN KEY (target_staff_id) REFERENCES staff(staff_id),

  CONSTRAINT swap_shift_fk
    FOREIGN KEY (shift_id) REFERENCES shift(shift_id),

  CONSTRAINT swap_not_self_chk
    CHECK (target_staff_id IS NULL OR target_staff_id <> requester_id)
);

CREATE TABLE fairness_index (
  fairness_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id       NUMBER NOT NULL,
  period_start   DATE NOT NULL,
  period_end     DATE NOT NULL,

  undesirable_shifts_count NUMBER(4) DEFAULT 0 CHECK (undesirable_shifts_count >= 0),
  weekend_shifts_count     NUMBER(4) DEFAULT 0 CHECK (weekend_shifts_count >= 0),
  fairness_score           NUMBER(5,2) CHECK (fairness_score BETWEEN 0 AND 100),

  CONSTRAINT fairness_staff_fk
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),

  CONSTRAINT fairness_period_chk
    CHECK (period_end >= period_start),

  CONSTRAINT fairness_staff_period_uk UNIQUE (staff_id, period_start, period_end)
);

-- =========================================================
-- Helpful indexes for performance
-- =========================================================
-- CREATE INDEX idx_shift_dept_start ON shift(department_id, shift_start);
-- CREATE INDEX idx_assignment_shift ON assignment(shift_id);
-- CREATE INDEX idx_assignment_staff ON assignment(staff_id);
-- CREATE INDEX idx_leave_staff_dates ON leave_request(staff_id, start_date, end_date);
-- CREATE INDEX idx_wellness_staff_date ON wellness_score(staff_id, date_recorded);