DROP TABLE IF EXISTS shift_assignment CASCADE;
DROP TABLE IF EXISTS shift CASCADE;
DROP TABLE IF EXISTS staff_qual CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS role CASCADE;



CREATE TABLE role (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    base_hourly_rate NUMERIC(8,2)
);

CREATE TABLE department (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL UNIQUE,
    location VARCHAR(100),
    ward_activity_score NUMERIC(4,2)
);

CREATE TABLE staff (
    staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE,
    phone VARCHAR(20),
    hire_date DATE NOT NULL,
    employment_type VARCHAR(50),
    status VARCHAR(30) DEFAULT 'ACTIVE',
    role_id INTEGER NOT NULL,
    primary_department_id INTEGER NOT NULL,

    CONSTRAINT staff_role_fk
        FOREIGN KEY (role_id)
        REFERENCES role(role_id),

    CONSTRAINT staff_department_fk
        FOREIGN KEY (primary_department_id)
        REFERENCES department(department_id)
);

CREATE TABLE staff_qual (
    department_id INTEGER NOT NULL,
    staff_id INTEGER NOT NULL,
    qualified_date DATE,
    certification_level VARCHAR(100),

    CONSTRAINT staff_qual_pk
        PRIMARY KEY (department_id, staff_id),

    CONSTRAINT staff_qual_staff_fk
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT staff_qual_department_fk
        FOREIGN KEY (department_id)
        REFERENCES department(department_id)
);

CREATE TABLE shift (
    shift_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL,
    shift_start TIMESTAMP NOT NULL,
    shift_end TIMESTAMP NOT NULL,
    shift_type VARCHAR(10) CHECK (shift_type IN ('DAY','NIGHT')),
    required_doctors INTEGER,
    required_nurses INTEGER,
    patient_ratio_score NUMERIC(4,2),
    spontaneity_score NUMERIC(4,2),

    CONSTRAINT shift_department_fk
        FOREIGN KEY (department_id)
        REFERENCES department(department_id),

    CONSTRAINT shift_time_check
        CHECK (shift_end > shift_start)
);


CREATE TABLE shift_assignment (
    assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    shift_id INTEGER NOT NULL,
    assignment_status VARCHAR(20) DEFAULT 'ASSIGNED',
    assigned_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT assignment_staff_fk
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT assignment_shift_fk
        FOREIGN KEY (shift_id)
        REFERENCES shift(shift_id),

    CONSTRAINT unique_staff_shift
        UNIQUE (staff_id, shift_id)
);

CREATE TABLE leave_request (
    leave_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    leave_type VARCHAR(20),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    approval_status VARCHAR(20) DEFAULT 'PENDING',
    date_submitted TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT leave_staff_fk
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT leave_date_check
        CHECK (end_date >= start_date)
);

CREATE TABLE workload_record (
    workload_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    week_start_date DATE NOT NULL,
    total_hours NUMERIC(5,2),
    night_shifts INTEGER,
    consecutive_days INTEGER,
    overtime_hours NUMERIC(5,2),

    CONSTRAINT workload_staff_fk
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT unique_staff_week
        UNIQUE (staff_id, week_start_date)
);

CREATE TABLE wellness_score (
    wellness_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    date_recorded DATE NOT NULL,
    fatigue_score INTEGER CHECK (fatigue_score BETWEEN 1 AND 10),
    stress_score INTEGER CHECK (stress_score BETWEEN 1 AND 10),
    sleep_hours NUMERIC(4,1),
    burnout_risk_level VARCHAR(10),

    CONSTRAINT wellness_staff_fk
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT unique_staff_date
        UNIQUE (staff_id, date_recorded)
);

CREATE TABLE incident_exposure (
    incident_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL,
    shift_id INTEGER,
    severity_level VARCHAR(10),
    emotional_weight_score NUMERIC(4,2),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT incident_staff_fk
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id),

    CONSTRAINT incident_shift_fk
        FOREIGN KEY (shift_id)
        REFERENCES shift(shift_id)
);